url: https://yumanoishii.github.io
baseurl: /ywport

# Site settings
title: YW Creations
email: your-email@domain.com
description: "YW's art gallery and thoughts"


# Team names, titles and social links
people:
- name: YW
  pic: 1
  position: Artist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty